services:
  postgres2:
    image: postgres:16
    container_name: project2-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lesson
      POSTGRES_DB: postgres
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata2:
